dataset: amazon_cs
num_epochs: 130
n_inject_max: 20
n_edge_max: 40
epsilon: 0.5
n_epoch_attack: 10
hid_dim: 256
n_heads:
- 8
- 1
n_layers: 2
feat_drop: 0.6
attn_drop: 0.6
lr: 0.001
weight_decay: 0.0005
