dataset: coauthor_cs
num_epochs: 200
early_stopping: 100
n_inject_max: 20
n_edge_max: 20
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 8
n_heads:
- 8
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.001
weight_decay: 0.0005
lambda_1: 1
lambda_2: 100000
lambda_3: 100000
K: 100000
K_rho: 100000
save_path: ./FGAI_checkpoints/