dataset: citeseer
num_epochs: 50
early_stopping: 30
n_inject_max: 15
n_edge_max: 25
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 512
n_heads:
- 16
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.0001
weight_decay: 0.0005
lambda_1: 1
lambda_2: 500
lambda_3: 500
K: 300
K_rho: 3000
save_path: ./FGAI_checkpoints/
