dataset: coauthor_cs
num_epochs: 400
early_stopping: 20
n_inject_max: 20
n_edge_max: 20
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 8
n_heads:
- 8
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.001
weight_decay: 0
lambda_1: 0.08
lambda_2: 0.01
lambda_3: 0.02
K: 60000
K_rho: 50000
save_path: ./FGAI_checkpoints/
