dataset: amazon_photo
num_epochs: 600
early_stopping: 1000
n_inject_max: 20
n_edge_max: 20
epsilon: 0.05
n_epoch_attack: 10
hid_dim: 8
n_heads:
- 8
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.01
weight_decay: 0.0005
lambda_1: 0.001
lambda_2: 5000
lambda_3: 5000
K: 150000
K_rho: 150000
save_path: ./FGAI_checkpoints/
