dataset: ogbn-arxiv
num_epochs: 200
early_stopping: 200
n_inject_max: 20
n_edge_max: 40
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 16
n_heads:
- 8
n_layers: 1
feat_drop: 0.05
attn_drop: 0
lr: 0.001
weight_decay: 0.0005
lambda_1: 1
lambda_2: 10000000
lambda_3: 50000000
K: 600000
K_rho: 600000
save_path: ./FGAI_checkpoints/
