dataset: pubmed
num_epochs: 80
early_stopping: 150
n_inject_max: 10
n_edge_max: 20
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 512
n_heads:
- 16
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.001
weight_decay: 0.0005
lambda_1: 1
lambda_2: 100000
lambda_3: 100000
K: 200000
K_rho: 200000
save_path: ./FGAI_checkpoints/