dataset: cora
num_epochs: 50
early_stopping: 150
n_inject_max: 10
n_edge_max: 20
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 512
n_heads:
- 16
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.0001
weight_decay: 0.0005
lambda_1: 0.2
lambda_2: 1000
lambda_3: 1000
K: 2500
K_rho: 2500
save_path: ./FGAI_checkpoints/
