dataset: pubmed
num_epochs: 200
early_stopping: 200
n_inject_max: 50
n_edge_max: 50
epsilon: 0.2
n_epoch_attack: 5
hid_dim: 8
n_heads: 8
n_layers: 1
feat_drop: 0.6
attn_drop: 0.6
lr: 0.01
weight_decay: 0.0005
lambda_1: 1
lambda_2: 10000
lambda_3: 10000
K: 20
K_rho: 20
save_path: ./FGAI_checkpoints/
