dataset: COLLAB
num_epochs: 100
batch_size: 32
n_inject_max: 20
n_edge_max: 40
epsilon: 0.1
n_epoch_attack: 10
hid_dim: 128
n_heads:
- 4
- 4
n_layers: 2
feat_drop: 0.3
attn_drop: 0.3
lr: 0.001
weight_decay: 0.0001
