dataset: amazon_cs
num_epochs: 100
early_stopping: 200
n_inject_max: 20
n_edge_max: 20
epsilon: 0.08
n_epoch_attack: 10
hid_dim: 256
n_heads:
- 8
- 1
n_layers: 2
feat_drop: 0.6
attn_drop: 0.6
lr: 0.001
weight_decay: 0.0005
lambda_1: 0.8
lambda_2: 100000
lambda_3: 100000
K: 100000
K_rho: 100000
save_path: ./FGAI_checkpoints/
